// <auto-generated />
namespace Library.Web.DataContexts.BookDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class SchemaChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SchemaChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201310142327073_SchemaChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
